# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 735)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatScroll = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.chatScroll.setWidgetResizable(True)
        self.chatScroll.setObjectName("chatScroll")
        self.chatContainer = QtWidgets.QWidget()
        self.chatContainer.setGeometry(QtCore.QRect(0, 0, 566, 672))
        self.chatContainer.setObjectName("chatContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.chatContainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chatLayout = QtWidgets.QVBoxLayout()
        self.chatLayout.setContentsMargins(10, 10, 10, 10)
        self.chatLayout.setSpacing(10)
        self.chatLayout.setObjectName("chatLayout")
        self.verticalLayout_4.addLayout(self.chatLayout)
        self.chatScroll.setWidget(self.chatContainer)
        self.verticalLayout.addWidget(self.chatScroll)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Chat = QtGui.QAction(parent=MainWindow)
        self.actionImport_Chat.setObjectName("actionImport_Chat")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionImport_Chat)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "Files"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_Chat.setText(_translate("MainWindow", "Import Chat"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
